blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$',
        views.post_detail, name='post_detail'),
    ]

website/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):

    def get_query(self):
        return super(PublishedManager, self).get_query().filter(status='publish')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)
    publish = models.DateField(default=timezone.now)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish', )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __unicode__(self):
        return 'Comment by {} on {} '.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post
from .forms import CommentForm


def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %} {% endblock %}</title>
    <link href="{% static "blog/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/blog.css" %}" rel="stylesheet">
</head>
<body>
    {% include 'blog/includes/navbar.html' %}
    {% block body %}



    {% endblock %}
    <script src="{% static 'blog/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/includes/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">Binary Blog</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
        <li><a href="#">Sign Up</a></li>
      </ul>
    </div>
  </div>
</nav>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %} {{ post.title }} {% endblock %}

{% block body %}
    <div class="container">
        <div class="row detail">
             <h1>{{ post.title }}</h1>

          <p class="date">
            Published {{ post.publish }} by {{ post.author }}
          </p>
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="">
        {% else %}
            <img class="img-responsive" src="{% static 'blog/img/w.jpg' %}" alt="">
        {% endif %}
        <br>
        {{ post.body|linebreaks }}

    {% with comments.count as total_comments %}
          <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
          </h2>
    {% endwith %}

            <hr>

    {% for comment in comments %}
      <div class="comment well">
        <p class="info"><strong>
          Comment {{ forloop.counter }} by {{ comment.name }}
          {{ comment.created }}
            </strong>
        </p>
        {{ comment.body|linebreaks }}
      </div>
    {% empty %}
  <p>There are no comments yet.</p>
    {% endfor %}


    {% if new_comment %}
      <h2>Your comment has been added.</h2>
    {% else %}
      <h2>Add a new comment</h2>
      <form action="." method="post">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <p ><input class="btn btn-default" type="submit" value="Add comment"></p>
      </form>
    {% endif %}

        </div>
    </div>


{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block title %} Home - My Blog {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
                <div class="row">
                    <div class="col-md-6 blog-img">
                        {% if post.image %}
                            <img class="img-responsive" src="{{ post.image.url }}" alt="">
                        {% else %}
                            <img class="img-responsive" src="{% static 'blog/img/w.jpg' %}" alt="">
                        {% endif %}
                    </div>

                    <div class="col-md-6 blog-detail">
                        <h2>
                          <a href="{{ post.get_absolute_url }}">
                            {{ post.title }}
                          </a>
                        </h2>

                        <p class="date">
                        Published {{ post.publish }} by {{ post.author }}
                        </p>
                        {{ post.body|truncatewords:100|linebreaks }}

                        <a href="{{ post.get_absolute_url }}">
                            <span class="btn btn-default">Read More</span>
                        </a>
                    </div>
                </div>
                <br><br>
            {% endfor %}

        </div>
    </div>
{% endblock %}